=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q01_IPsy/Questionnaire.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT questionnaire (description,questions,tags?,remarks?)>

<!ELEMENT description (identifier,caption,information,questionsnum?,interfacetype?)>
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT information (#PCDATA)>
<!ELEMENT questionsnum (#PCDATA)>
<!ELEMENT interfacetype (#PCDATA)>

<!ELEMENT questions (question+)>
<!ELEMENT question (title,answer*)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST question
	qid CDATA #REQUIRED
	tag CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer
	aid CDATA #REQUIRED
	score CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
	name CDATA #REQUIRED
	label CDATA #REQUIRED
>

<!ELEMENT remarks (remark+)>
<!ELEMENT remark (#PCDATA)>
<!ATTLIST remark
	tag CDATA #IMPLIED
	minScore CDATA #REQUIRED
	maxScore CDATA #REQUIRED
>

=== Yufang0828/PsyMap/quizlite/quiz/Q00/EQ.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	此问卷由心理所提供，问题参见Word文档《情绪智力网络测量方案》。
	共四个维度，每个维度4道题，在李克特五点量表上评分，计算平均分。所有题汇总，有一个情绪智力的总平均分，即：

	情绪智力：1-16题
	自我情绪评估：1-4题
	他人情绪评估：5-8题
	情绪使用：9-12题
	情绪调节：13-16题
-->

<questionnaire>
  <description>
    <identifier>EQ</identifier>
    <caption>情绪智力网络测量</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是针对情绪智力网络调查而设计的。您填写的信息结果将用于我们进行科学研究，十分感谢您的合作！
	
	情绪智力于1990年由美国耶鲁大学心理学家Salovey和Mayer提出来。1995年，美国哈佛大学心理学教授Goleman出版了《情商：为什么情商比智商更重要》一书，真正引发了社会的广泛关注和学术界的大量研究。Goleman教授的书中，情绪智力被翻译为更容易引起社会关注的“情商”，其英文与情绪智力相同，都是Emotional Intelligence。情绪智力概念的出现，在一定程度上解释了“有的人非常聪明但缺乏自我控制能力，很难与别人融洽相处，而有的人资质平平却可以获得成果”的现象。情绪智力对人的职业生涯发展和心理、生活健康的影响可能比我们现在实证研究得到的统计学上的贡献率更高。Goleman教授的研究显示，领导力的竞争力模式通常包含以情商为基础的各项能力，贡献率为80%-100%不等。情绪智力在国外已经引起了广泛重视，积累了大量的覆盖各类职业人群的实证研究数据，但在中国，关于“情商”的热潮仍然还停留在感性阶段，与情绪智力有关的实证研究少之又少。]]>
	</information>
	<interfacetype>CompareToAverage</interfacetype>
  </description>

  <questions>
	<question qid="q1" tag="sa ei">
		<title>大部分时候我都很清楚自己为什么会有某种感受</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
  
    <question qid="q2" tag="sa ei">
		<title>我很了解自己的情绪</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q3" tag="sa ei">
		<title>我明白自己的感受</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q4" tag="sa ei">
		<title>我总是知道自己是不是高兴</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q5" tag="oa ei">
		<title>我总是能从朋友的行为中感受到他/她的情绪</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q6" tag="oa ei">
		<title>对于别人的情绪，我是个很好的观察者</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q7" tag="oa ei">
		<title>我对别人的情绪和感受很敏感</title>
     <answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q8" tag="oa ei">
		<title>我能够很好地感受到身边人们的情绪</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>

	<question qid="q9" tag="eu ei">
		<title>我总是给自己确定目标并努力去实现</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>

	<question qid="q10" tag="eu ei">
		<title>我总是告诉自己我能行</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q11" tag="eu ei">
		<title>我是个自我激励型的人</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q12" tag="eu ei">
		<title>我总是鼓励自己要尽最大努力去做事情</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q13" tag="ea ei">
		<title>我能控制自己的情绪，因此能够理性对待困难</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q14" tag="ea ei">
		<title>我完全能够控制自己的情绪</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q15" tag="ea ei">
		<title>当我非常愤怒的时候，我能很快让自己平静下来</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
	<question qid="q16" tag="ea ei">
		<title>我对自己的情绪有很好的控制力</title>
		<answer aid="a" score="1">不同意</answer>
		<answer aid="b" score="2">有点不同意</answer>
		<answer aid="c" score="3">不清楚</answer>
		<answer aid="d" score="4">有点同意</answer>
		<answer aid="e" score="5">同意</answer>
    </question>
	
  </questions>

  <tags>
	<tag name="sa" label="自我情绪评估"><![CDATA[评分在0~5分之间。指能够了解自己内心的真正感受并且自然地表达出来的能力。这方面能力突出的个体比其他人更容易觉察和理解自己的情绪。]]></tag>
	<tag name="oa" label="他人情绪评估"><![CDATA[评分在0~5分之间。指能够感觉到周围其他人的情绪的能力。这种能力比较高，意味着能够敏锐地发觉他人内心深处的感觉与情绪。]]></tag>
	<tag name="eu" label="情绪使用"><![CDATA[评分在0~5分之间。指能够很好地控制自己的情绪状态，并且能够使自己从不良的情绪体验中迅速恢复过来的能力。请注意，这项能力特别指个体能够在负面情绪状态下仍然很好地控制自身情绪。这项能力高的人，可以快速调整与排除心理不良的情绪状态，然后还能表达出正面的情绪。因此，这种现象也被解读为“自我激励”。]]></tag>
	<tag name="ea" label="情绪调节"><![CDATA[评分在0~5分之间。指能够灵活运用自己的情绪、引导出积极的行为，同时能够自觉远离不良情绪困扰的能力。这项能力得分高的人往往可以在陷入极端情绪时仍然很好地控制自己的言行举止。]]></tag>
	<tag name="ei" label="情绪智力"><![CDATA[评分在0~5分之间。这一维度是对您回答的所有问题的平均，综合体现了您的情绪智力评估状况。]]></tag>
  </tags>
  
  <remarks>
    <remark tag="sa" minScore="min" maxScore="avg">您的得分低于平均分，属于低分组。</remark>
	<remark tag="sa" minScore="avg" maxScore="max">您的得分高于平均分，属于高分组。</remark>
	<remark tag="oa" minScore="min" maxScore="avg">您的得分低于平均分，属于低分组。</remark>
	<remark tag="oa" minScore="avg" maxScore="max">您的得分高于平均分，属于高分组。</remark>
	<remark tag="eu" minScore="min" maxScore="avg">您的得分低于平均分，属于低分组。</remark>
	<remark tag="eu" minScore="avg" maxScore="max">您的得分高于平均分，属于高分组。</remark>
	<remark tag="ea" minScore="min" maxScore="avg">您的得分低于平均分，属于低分组。</remark>
	<remark tag="ea" minScore="avg" maxScore="max">您的得分高于平均分，属于高分组。</remark>
	<remark tag="ei" minScore="min" maxScore="avg">您的得分低于平均分，属于低分组。</remark>
	<remark tag="ei" minScore="avg" maxScore="max">您的得分高于平均分，属于高分组。</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/quizlite/quiz/Q08_BJ/Happiness.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
幸福感：
	Satisfaction With Life Scale (Pavot & Diener, 1993) q01~q05
	情感量表：正性情感、负性情感、情感平衡 q06~q15 : p n p n p n p n p n
-->

<questionnaire>
  <description>
    <identifier>Happiness</identifier>
    <caption>幸福感测量</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是用于衡量填写者的幸福感的。通过填写本量表，您可以评测您的幸福感。]]>
	</information>
    <interfacetype>CompareToAverage</interfacetype>
  </description>

  <questions>
  
	<question qid="q01" tag="swls">
      <title>我的生活大致符合我的理想。</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">不同意</answer>
	  <answer aid="c" score="3">少许不同意</answer>
	  <answer aid="d" score="4">中立</answer>
	  <answer aid="e" score="5">少许同意</answer>
	  <answer aid="f" score="6">同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
  
  	<question qid="q02" tag="swls">
      <title>我的生活状况非常圆满。</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">不同意</answer>
	  <answer aid="c" score="3">少许不同意</answer>
	  <answer aid="d" score="4">中立</answer>
	  <answer aid="e" score="5">少许同意</answer>
	  <answer aid="f" score="6">同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q03" tag="swls">
      <title>我满意自己的生活。</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">不同意</answer>
	  <answer aid="c" score="3">少许不同意</answer>
	  <answer aid="d" score="4">中立</answer>
	  <answer aid="e" score="5">少许同意</answer>
	  <answer aid="f" score="6">同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q04" tag="swls">
      <title>直到现在为止，我都能够得到我在生活上希望拥有的重要东西。</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">不同意</answer>
	  <answer aid="c" score="3">少许不同意</answer>
	  <answer aid="d" score="4">中立</answer>
	  <answer aid="e" score="5">少许同意</answer>
	  <answer aid="f" score="6">同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q05" tag="swls">
      <title>如果我能重新活过，差不多没有东西我想改变。</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">不同意</answer>
	  <answer aid="c" score="3">少许不同意</answer>
	  <answer aid="d" score="4">中立</answer>
	  <answer aid="e" score="5">少许同意</answer>
	  <answer aid="f" score="6">同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q06" tag="pa">
      <title>在过去几周里你是否感到：对某事特别热衷或特别感兴趣？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
	
	<question qid="q07" tag="na">
      <title>在过去几周里你是否感到：感到坐立不安？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q08" tag="pa">
      <title>在过去几周里你是否感到：因为别人对你工作的赞扬而感到骄傲？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q09" tag="na">
      <title>在过去几周里你是否感到：十分孤独或远离他人？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q10" tag="pa">
      <title>在过去几周里你是否感到：由于完成了某项工作而感到愉快？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q11" tag="na">
      <title>在过去几周里你是否感到：心烦？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q12" tag="pa">
      <title>在过去几周里你是否感到：仿佛处在世界的顶峰（有飘然的感觉）？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q13" tag="na">
      <title>在过去几周里你是否感到：忧郁或非常不幸福？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q14" tag="pa">
      <title>在过去几周里你是否感到：事情在按你的意愿发展？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>
    
	<question qid="q15" tag="na">
      <title>在过去几周里你是否感到：由于某人的批评而感到不安？</title>
      <answer aid="y" score="1">是</answer>
      <answer aid="n" score="0">否</answer>
    </question>

  </questions>
  
  <tags>
	<tag name="swls" label="生活满意度"><![CDATA[本维度表征填写者对生活的满意程度。]]></tag>
	<tag name="pa"   label="正性情感"><![CDATA[本维度表征填写者在过去几周中的正性情感。]]></tag>
	<tag name="na"   label="负性情感"><![CDATA[本维度表征填写者在过去几周中的负性情感]]></tag>
  </tags>

  <remarks>
	<remark tag="swls" minScore="min" maxScore="avg">您的得分低于平均水平。</remark>
    <remark tag="swls" minScore="avg" maxScore="max">您的得分高于平均水平。</remark>
    <remark tag="pa"   minScore="min" maxScore="avg">您的得分低于平均水平。</remark>
    <remark tag="pa"   minScore="avg" maxScore="max">您的得分高于平均水平。</remark>
    <remark tag="na"   minScore="min" maxScore="avg">您的得分低于平均水平。</remark>
    <remark tag="na"   minScore="avg" maxScore="max">您的得分高于平均水平。</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/quizlite/quiz/Q02_2K/Q2_SSQ6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	状态-特质焦虑量表，原问卷共有40道题目（状态、特质各20题），
	插入了11道测谎题和自我粉饰题，用tag=M和tag=E标出。
-->

<questionnaire>
  <description>
    <identifier>Q2_MBSupport</identifier>
    <caption>微博使用社会支持感测试问卷</caption>
    <information><![CDATA[　　下列问题描述了你自己在使用微博时可能会从其它用户那里获得的帮助或支持。每个问题都需要你回答两部分的内容。

　　第一部分，请你填写自己在使用微博时能够像题目中描述得那样向你提供该种帮助或支持的用户人数（填写的人数需要能够清晰地对应到每个具体的用户）。
　　第二部分，请你标出自己在总体上对于能够从其它用户那里获得该种帮助或支持的情况的满意度。

　　请您在不受外界打扰的情况下，认真、真实地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1" type="text">
		<title>当你感觉精神紧张时，在微博上有一些人能够帮你从烦恼中解脱出来，这样的人的人数有：</title>
	</question>

	<question qid="q2">
		<title>像上一题描述的那样，当你感觉精神紧张，而在微博上有那些人能够帮你从烦恼中解脱出来时，你对能从他们那里获得的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>

	<question qid="q3" type="text">
		<title>当你感觉压力或焦虑时，在微博上有一些人能够帮使你的心情放松，这样的人的人数有：</title>
	</question>

	<question qid="q4">
		<title>像上一题描述的那样，当你感觉精神紧张，而在微博上有那些人能够使你放松时，你对能从他们那里获得的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>
	
	<question qid="q5" type="text">
		<title>在微博上有人能够完全接纳你，包括你的优点和缺点，这样的人的人数为：</title>
	</question>

	<question qid="q6">
		<title>像上一题描述的那样，对于那些在微博上有那些能够完全接纳你的人，包括你的优点和缺点，你对能从他们那里获得的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>
	
	<question qid="q7" type="text">
		<title>无论你发生了什么，在微博上有一些人会关心你，这样的人的人数为：</title>
	</question>

	<question qid="q8">
		<title>像上一题描述的那样，对于那些无论发生什么，在微博上都会关心你的那些人，你对他们提供的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>
	
	<question qid="q9" type="text">
		<title>当你感觉情绪低落时，在微博上有人能够使你的心情愉快一些，这样的人的人数为：</title>
	</question>

	<question qid="q10">
		<title>像上一题描述的那样，当你感觉情绪低落，而那些在微博上有那些人能够使你的心情愉快时，你对他们给你提供的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>
	
	<question qid="q11" type="text">
		<title>当你感觉心烦意乱时，在微博上有一些人能够安慰你，这样的人的人数为：</title>
	</question>

	<question qid="q12">
		<title>像上一题描述的那样，当你感觉心烦意乱，而在微博上有那些人能够安慰你时，你对能从他们那里获得的帮助感到：</title>
		<answer aid="a" score="1">非常不满意</answer>
		<answer aid="b" score="2">比较不满意</answer>
		<answer aid="c" score="3">不满意</answer>
		<answer aid="d" score="4">满意</answer>
		<answer aid="e" score="5">比较满意</answer>
		<answer aid="f" score="6">非常满意</answer>
	</question>
	
  </questions>

  <remarks>
	<remark minScore="min" maxScore="max">非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q05_Sina/SINA_SAS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<questionnaire>
  <description>
    <identifier>SINA_SAS</identifier>
    <caption>心理焦虑状况测量量表</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是针对焦虑评价而设计的。通过填写本量表，您可以评测您的焦虑状况。下面有二十条文字，请仔细阅读每一条，把意思弄明白，然后根据您最近一星期的实际感受，选择与您的感受最相符的选项。]]>
	</information>
  </description>

  <questions>
    <question qid="q01" tag="A">
      <title>最近一星期以来，我觉得比平常容易紧张或着急</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q02" tag="A">
      <title>最近一星期以来，我无缘无故地感到害怕</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q03" tag="A">
      <title>最近一星期以来，我容易心里烦乱或觉得惊恐</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q04" tag="A">
      <title>最近一星期以来，我觉得我可能将要发疯</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q05" tag="A">
      <title>最近一星期以来，我觉得一切都很好，也不会发生什么不幸</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q06" tag="A">
      <title>最近一星期以来，我手脚发抖打颤</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q07" tag="A">
      <title>最近一星期以来，我因为头痛、颈痛和背痛而苦恼</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q08" tag="A">
      <title>最近一星期以来，我感到容易衰弱和疲乏</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q09" tag="A">
      <title>最近一星期以来，我得心平气和，并且容易安静坐着</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q10" tag="A">
      <title>最近一星期以来，我觉得心跳得很快</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q11" tag="A">
      <title>最近一星期以来，我因为一阵阵头晕而苦恼</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q12" tag="A">
      <title>最近一星期以来，我有晕倒发作，或觉得要晕倒似的</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q13" tag="A">
      <title>最近一星期以来，我呼气吸气都感到很容易</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q14" tag="A">
      <title>最近一星期以来，我的手脚麻木和刺痛</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q15" tag="A">
      <title>最近一星期以来，我因为胃痛和消化不良而苦恼</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q16" tag="A">
      <title>最近一星期以来，我常常要小便</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q17" tag="A">
      <title>最近一星期以来，我的手脚常常是干燥温暖的</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q18" tag="A">
      <title>最近一星期以来，我脸红发热</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q19" tag="A">
      <title>最近一星期以来，我容易入睡，晚上休息很好</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q20" tag="A">
      <title>最近一星期以来，我做恶梦</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>
  </questions>
  
   <tags>
	<tag name="A" label="心理焦虑"><![CDATA[本问卷对您的焦虑状况进行了测评。]]>
	</tag>
   </tags>
   
   <remarks>
    <remark tag="A" minScore="min" maxScore="20">你的分数处于低水平范围：根据问卷的得分显示，你在此刻并没有或只有很少的焦虑症状，并没有深陷于焦虑情绪的困扰。如果你觉得自己可能已经陷入了焦虑情绪状态，那么建议你立刻去求助于专业的心理咨询人员。</remark>
    <remark tag="A" minScore="20" maxScore="40">你的分数处于中等水平范围：你可能有轻微或轻度焦虑情绪问题。建议你寻求专业性的建议与指导，从而帮助你提高自身的情绪应对能力并在未来免遭类似的消极情绪困扰。</remark>
    <remark tag="A" minScore="40" maxScore="max">你的分数处于高水平范围：这说明在你身上具有比其他人更多的焦虑症状。你可能比较容易遭到焦虑情绪的侵袭。我们建议你去向专业的心理咨询或治疗人员寻求帮助，从而彻底检查自己的心理健康状态。</remark>
   </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q02_2K/Q2_SIAnx.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	交往焦虑量表，原问卷共有15道题目，
	插入了8道测谎题和自我粉饰题，用tag=M和tag=E标出。
-->

<questionnaire>
  <description>
    <identifier>Q2_STAnx</identifier>
    <caption>社会交往状况调查问卷</caption>
    <information><![CDATA[　　欢迎您填写本量表，后面的题目列出了一些与您在社会交往中的感受相关的问题。
　　请您认真阅读下面的每个题目，并决定其陈述对你适用或其真实的程度，选择你认同的选项。

　　请您在不受外界打扰的情况下，认真、真实地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
		<title>即时在非正式的聚会上，我也常感到紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>
	
	<question qid="M138" tag="M">
		<title>批评和责骂都使我非常伤心。</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>

    <question qid="q2">
		<title>与一群不认识的人在一起时，我通常感到不自在</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>

	<question qid="q3">
		<title>在与一位异性交谈时我通常感到轻松</title>
		<answer aid="a" score="5">一点儿也不相符</answer>
		<answer aid="b" score="4">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="2">非常相符</answer>
		<answer aid="e" score="1">极其相符</answer>
    </question>

	<question qid="q4">
		<title>在必须同老师或上司谈话时，我感到紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>
	
	<question qid="E12" tag="E">
		<title>若你说过要做某件事，是否不管遇到什么困难都要把它做成？</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>

	<question qid="q5">
		<title>聚会常会使我感到焦虑及不自在</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>
	
	<question qid="E4" tag="E">
		<title>当别人做了好事，而周围的人却认为是你做的时候，你是否感到洋洋得意？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q6">
		<title>与大多数人相比，我在社会交往中可能较少羞怯</title>
		<answer aid="a" score="5">一点儿也不相符</answer>
		<answer aid="b" score="4">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="2">非常相符</answer>
		<answer aid="e" score="1">极其相符</answer>
    </question>
	
	<question qid="q7">
		<title>在与我不太熟悉的同性谈话时，我常常感到紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>

	<question qid="M180" tag="M">
		<title>我觉得我遇到生人的时候就不知道说什么好了</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q8">
		<title>在求职面试时我会紧张的</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>

	<question qid="q9">
		<title>我希望自己在社交场合中信心更足一些</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
	</question>
	
	<question qid="E31" tag="E">
		<title>你在儿童时代是否立即听从大人的吩咐而毫无怨言？</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>

	<question qid="q10">
		<title>在社交场合中，我很少感到焦虑</title>
		<answer aid="a" score="5">一点儿也不相符</answer>
		<answer aid="b" score="4">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="2">非常相符</answer>
		<answer aid="e" score="1">极其相符</answer>
    </question>
	
	<question qid="q11">
		<title>一般而言，我是一个害羞的人</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>
	
	<question qid="E64" tag="E">
		<title>你曾经是否坚持要照你的想法办事？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q12">
		<title>在与一位迷人的异性交谈时我经常感到紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>

	<question qid="E83" tag="E">
		<title>你是否有过随口骂人的时候？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

	<question qid="q13">
		<title>给不太熟的人打电话时我通常觉得紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>

	<question qid="q14">
		<title>我在与权威人士谈话时感到紧张</title>
		<answer aid="a" score="1">一点儿也不相符</answer>
		<answer aid="b" score="2">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="4">非常相符</answer>
		<answer aid="e" score="5">极其相符</answer>
    </question>
	
	<question qid="q15">
		<title>即使处于一群和我相当不同的人群之中，通常我仍感到放松</title>
		<answer aid="a" score="5">一点儿也不相符</answer>
		<answer aid="b" score="4">有一点儿相符</answer>
		<answer aid="c" score="3">中等程度相符</answer>
		<answer aid="d" score="2">非常相符</answer>
		<answer aid="e" score="1">极其相符</answer>
	</question>
	
	<question qid="M406" tag="M">
		<title>我有时回避见人，因为我怕我会做出或讲出一些事后令我懊悔的事</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>
	
  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>
