=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q01_IPsy/Questionnaire.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT questionnaire (description,questions,tags?,remarks?)>

<!ELEMENT description (identifier,caption,information,questionsnum?,interfacetype?)>
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT information (#PCDATA)>
<!ELEMENT questionsnum (#PCDATA)>
<!ELEMENT interfacetype (#PCDATA)>

<!ELEMENT questions (question+)>
<!ELEMENT question (title,answer*)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST question
	qid CDATA #REQUIRED
	tag CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer
	aid CDATA #REQUIRED
	score CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
	name CDATA #REQUIRED
	label CDATA #REQUIRED
>

<!ELEMENT remarks (remark+)>
<!ELEMENT remark (#PCDATA)>
<!ATTLIST remark
	tag CDATA #IMPLIED
	minScore CDATA #REQUIRED
	maxScore CDATA #REQUIRED
>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q01_IPsy/P3_Continuous.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	此问卷由心理所提供，源问卷参见Word文件《第三部分 持续使用意愿》。
-->

<questionnaire>
  <description>
    <identifier>Q1_Continuous</identifier>
    <caption>微博持续使用意愿调查</caption>
    <information><![CDATA[欢迎您填写本问卷调查，本调查是针对微博持续使用意愿用而设计的。
您的填写结果将用作科学研究之用，谢谢您的积极配合！]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
      <title>新浪微博带给我的经验和感受比我预期的要好</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
  
    <question qid="q2">
      <title>新浪微博对我很有用</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q3">
      <title>与我联系的许多人都使用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q4">
      <title>使用新浪微博已经成为我的一种习惯了</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q5">
      <title>比起停用新浪微博，我更希望能接着使用它</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q6">
      <title>新浪微博已经成为我解决问题的一种方法了</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q7">
      <title>总体来说，使用新浪微博是有益的</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q8">
      <title>如果可以，我希望就此停用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q9">
      <title>我平时经常联系的人们很多都使用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q10">
      <title>新浪微博提供的服务水平比我预期的要好</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q11">
      <title>新浪微博的优点多于它的缺点</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q12">
      <title>跟我联系的人们会继续使用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q13">
      <title>比起其他微博工具，我更希望能接着使用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q14">
      <title>总的来说，在使用新浪微博的过程中，我大部分的预期得到了满足</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q15">
      <title>我已经可以轻松自如地使用新浪微博了</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
	<question qid="q16">
      <title>现在跟我联系并使用新浪微博的人们以后也会继续使用新浪微博</title>
      <answer aid="a" score="1">非常不同意</answer>
      <answer aid="b" score="2">比较不同意</answer>
	  <answer aid="c" score="3">不太同意</answer>
	  <answer aid="d" score="4">不确定</answer>
	  <answer aid="e" score="5">同意</answer>
	  <answer aid="f" score="6">比较同意</answer>
	  <answer aid="g" score="7">非常同意</answer>
    </question>
	
  </questions>

  <tags>
	<tag name="" label="致谢"><![CDATA[非常感谢您填写我们的问卷调查！]]></tag>
  </tags>

  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用作科学研究。</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q02_2K/Q2_CES-D.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	流调中心用抑郁焦虑量表，原问卷共有20道题目，
	插入了8道测谎题和自我粉饰题，用tag=M和tag=E标出。
-->

<questionnaire>
  <description>
    <identifier>Q2_CES-D</identifier>
    <caption>心理抑郁状况调查问卷</caption>
    <information><![CDATA[　　欢迎您填写本量表！
　　后面的题目描述了您可能存在的或最近有过的感受，请在每一道题目后点击选择合适的数字来表示在【最近一周来】您产生这种感受的频繁度。

　　请您在不受外界打扰的情况下，认真、真实地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
		<title>最近一周来，我为一些在平常并不会烦我的事而烦扰。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
  
	<question qid="q2">
		<title>最近一周来，我不想吃东西，食欲很差。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q3">
		<title>最近一周来，即使在家人或朋友的帮助下，我还觉得摆脱不了忧郁。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="E81" tag="E">
		<title>在公园里或马路上，你是否总是把果皮或废纸扔到垃圾箱里？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q4">
		<title>最近一周来，我感到我和别人一样好。</title>
		<answer aid="a" score="4">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="3">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="2">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="1">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="E7" tag="E">
		<title>你曾经有过贪心使自己多得份外的物质利益吗?</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q5">
		<title>最近一周来，我难以把心思集中于正在做的事情上。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="q6">
		<title>最近一周来，我感到沮丧。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="M89" tag="M">
		<title>要使大数人相信事实的真相，是要经过一番辩论的。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

	<question qid="q7">
		<title>最近一周来，我感到自己所做的每一件事都很费力。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="q8">
		<title>最近一周来，我对前途充满希望。</title>
		<answer aid="a" score="4">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="3">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="2">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="1">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="M129" tag="M">
		<title>我自己时常弄不清为什么会这样爱生气和发牢骚。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

	<question qid="q9">
		<title>最近一周来，我认为我的一生是一个失败。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="q10">
		<title>最近一周来，我感到害怕。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="q11">
		<title>最近一周来，我睡不安稳。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

	<question qid="E68" tag="E">
		<title>我的言行总是一致的。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

	<question qid="q12">
		<title>最近一周来，我很快乐。</title>
		<answer aid="a" score="4">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="3">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="2">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="1">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q13">
		<title>最近一周来，我比平常说话少了。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="M461" tag="E">
		<title>我希望我能避免因为破口伤人而引起的烦恼。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q14">
		<title>最近一周来，我感到孤独寂寞。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q15">
		<title>最近一周来，人们对我不友善。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="E171" tag="E">
		<title>在聚会当中，尽管有人出风头，如果让我也这样做，我会感到很不舒服。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q16">
		<title>最近一周来，我享受生活的惬意。</title>
		<answer aid="a" score="4">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="3">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="2">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="1">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q17">
		<title>最近一周来，我曾一阵阵的哭过。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q18">
		<title>最近一周来，我感到悲伤。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="M39" tag="E">
		<title>有时我真想摔东西。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q19">
		<title>最近一周来，我感到别人不喜欢我。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>
	
	<question qid="q20">
		<title>最近一周来，我提不起劲儿来做事。</title>
		<answer aid="a" score="1">极少或从未有过（少于1天）</answer>
		<answer aid="b" score="2">较少的时候是这样（1~2天）</answer>
		<answer aid="c" score="3">较多的时候是这样（3~4天）</answer>
		<answer aid="d" score="4">大多数或所有的时候都是这样（5~7天）</answer>
    </question>

  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="16">非常感谢您填写我们的问卷！</remark>
	<remark minScore="16" maxScore="max">感谢您的填写！您有一定的可能性存在抑郁的情况，</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q01_IPsy/P5_WeiboBasic.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<questionnaire>
  <description>
    <identifier>Q1_Weibo</identifier>
    <caption>微博使用情况测试量表</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是针对微博使用而设计的。通过填写本量表，您可以评测您的性格。]]>
	</information>
    <interfacetype>CompareToAverage</interfacetype>
  </description>

  <questions>
	<question qid="sex">
      <title>您的性别：</title>
      <answer aid="m" score="0">男性</answer>
      <answer aid="f" score="1">女性</answer>
    </question>
  
    <question qid="nation">
      <title>您的民族：</title>
      <answer aid="h" score="0">汉族</answer>
      <answer aid="o" score="1">其它少数民族</answer>
    </question>

    <question qid="age">
      <title>您的年龄段：</title>
      <answer aid="l16" score="1">16岁</answer>
      <answer aid="l18" score="2">16~18岁</answer>
      <answer aid="l22" score="3">18~22岁</answer>
      <answer aid="l27" score="4">22~27岁</answer>
      <answer aid="l35" score="5">27~35岁</answer>
	  <answer aid="l45" score="6">35~45岁</answer>
	  <answer aid="l55" score="7">45~55岁</answer>
	  <answer aid="l65" score="8">55~65岁</answer>
	  <answer aid="g65" score="9">>65岁</answer>
    </question>

    <question qid="in">
      <title>您的家庭月收入：</title>
      <answer aid="l2k" score="1">2000元以下</answer>
      <answer aid="l4k" score="2">2000—4000元</answer>
      <answer aid="l6k" score="3">4001—6000元</answer>
      <answer aid="l8k" score="4">6001—8000元</answer>
      <answer aid="l10k" score="5">8001—10000元</answer>
	  <answer aid="g10k" score="6">10000元以上</answer>
    </question>

    <question qid="edu">
      <title>您的受教育程度：</title>
      <answer aid="no" score="1">小学以下</answer>
      <answer aid="pr" score="2">小学</answer>
      <answer aid="md" score="3">初中</answer>
      <answer aid="hi" score="4">高中</answer>
      <answer aid="ug" score="5">大学本科（第二学位）</answer>
	  <answer aid="ms" score="6">硕士研究生</answer>
	  <answer aid="dr" score="7">博士研究生</answer>
    </question>

    <question qid="liv">
      <title>家庭所在地：</title>
      <answer aid="ci" score="1">城市</answer>
      <answer aid="to" score="2">乡镇</answer>
      <answer aid="vi" score="3">农村</answer>
    </question>

    <question qid="stu">
      <title>是否为学生在读：</title>
      <answer aid="y" score="0">是</answer>
      <answer aid="n" score="1">否</answer>
    </question>

    <question qid="regT">
      <title>注册“微博”账户的时间长度：</title>
      <answer aid="l1" score="1">小于1年</answer>
      <answer aid="y1" score="2">1年</answer>
      <answer aid="y2" score="3">2年</answer>
      <answer aid="y3" score="4">3年</answer>
	  <answer aid="y4" score="5">4年</answer>
	  <answer aid="y5" score="6">5年</answer>
	  <answer aid="y6" score="7">6年</answer>
      <answer aid="g6" score="8">大于6年</answer>
    </question>

    <question qid="rlPic">
      <title>在“微博”中是否上传真实头像：</title>
      <answer aid="t" score="0">是</answer>
      <answer aid="f" score="1">否</answer>
    </question>

    <question qid="rlNm">
      <title>在“微博”中使用真实姓名：</title>
      <answer aid="t" score="0">是</answer>
      <answer aid="f" score="1">否</answer>
    </question>

    <question qid="rlCnt">
      <title>在“微博”中公开个人联系方式（电话、邮箱、QQ、MSN）：</title>
      <answer aid="t" score="0">是</answer>
      <answer aid="f" score="1">否</answer>
    </question>

    <question qid="friSex">
      <title>您在‘微博’个人账户中多数好友的性别是：</title>
      <answer aid="m" score="0">男性</answer>
      <answer aid="f" score="1">女性</answer>
    </question>
  </questions>

  <remarks>
    <remark minScore="min" maxScore="max">非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q07_SCD/BeckSIS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
自杀意念量表

评分规则：
量表答案的选项为 3个，从左至右对应得分为 1、 2、 3。总得分越高，自杀意念越强烈。
测试者首先完成前 5 个题，如果第4 和第 5 个项目的选择答案都是“ 没有” , 那么则视为没有自杀意念，问卷结束。如果第 4 或者第 5 个项目任意 1 个选择答案是“ 弱” 或者“ 中等到强烈” ，那么就认定为有自杀意念，需要继续完成后面的 14 个项目。
对后 14 个项目修订时，为了方便评估，对个别项目(如 6、 7、 11、 13 和 19)的答案增加 1 个“ 近 1 周无自杀想法” 的选项,其对应得分为“ 0” 。

sI 自杀意念
自杀意念的强度是根据量表 1～5 项的均值所得，分数越高, 自杀意念的强度越大。

sD 自杀危险
自杀危险是依据量表的 6～19项来评估有自杀意念的被试真正实施自杀的可能性的大小。
总分的计算公式是[ ( 条目 6～19 的得分之和- 9) / 33] * 100,得分在 0～100 之间变化。分数越高，自杀危险性越大。

【备注】程序计分提示：
因程序目前尚未支持自动跳转，而本问卷的计分要求根据用户对第4、5题的选择来进行计分跳转；
故在这里使用要求如果用户第4、5题选择为结束跳转选项（都没有自杀意念）的情况下， 要求用户在后续题目当中都填写无，
后面的14道题目中有5道第一项为0，有9道第一项为1，故在题目qid="dem"中设置-9分，则sD维度得分自动为0。
如果用户需要填写后14道题目，则根据计分规则，也是将6~19道题的得分总和-9，然后再除以100/33，故最后给出的该维度的得分应当为sD*100/33。
-->

<questionnaire>
  <description>
    <identifier>BeckSIS</identifier>
    <caption>Beck自杀意念量表</caption>
    <information><![CDATA[　　欢迎您填写本量表，以下陈述是用来描述个人感觉和行为的，请仔细阅读每个句子，并选择适合你陈述。请根据您的实际情况进行填写，确保填好每个题目。
	【温馨提示】没有反馈信息。
　　本问卷为调查性问卷，我们向您承诺，我们会严格遵守协议，将您的填写结果将只用于科学研究，绝不会以任何形式泄漏您的隐私。请您放心填写真实信息。
　　请您在不受外界打扰的情况下，认真、真实、连续地填写完成本问卷。]]>
	</information>
  </description>

  <questions>

	<question qid="q1" tag="sI">
		<title>您希望活下去的程度如何？</title>
		<answer aid="a" score="0">中等到强烈</answer>
		<answer aid="b" score="0">弱</answer>
		<answer aid="c" score="0">没有活着的欲望</answer>
    </question>

	<question qid="q2" tag="sI">
		<title>您希望死去的程度如何？</title>
		<answer aid="a" score="0">没有死去的欲望</answer>
		<answer aid="b" score="0">弱</answer>
		<answer aid="c" score="0">中等到强烈</answer>
    </question>
	
	<question qid="q3" tag="sI">
		<title>我觉得我容易冲动</title>
		<answer aid="a" score="0">要活下去胜过要死去</answer>
		<answer aid="b" score="0">二者相当</answer>
		<answer aid="c" score="0">要死去胜过要活下来</answer>
    </question>
	
	<question qid="q4" tag="sI">
		<title>您主动尝试自杀的愿望程度如何？</title>
		<answer aid="a" score="0">没有</answer>
		<answer aid="b" score="0">弱</answer>
		<answer aid="c" score="0">中等到强烈</answer>
    </question>
	
	<question qid="q5" tag="sI">
		<title>您希望外力结束自己生命，即有“被动自杀愿望”的程度如何？（如，希望一直睡下去不再醒来、意外地死去等）</title>
		<answer aid="a" score="0">没有</answer>
		<answer aid="b" score="0">弱</answer>
		<answer aid="c" score="0">中等到强烈</answer>
    </question>
	
	<question qid="q6" tag="sD">
		<title>您的这种自杀想法持续存在多长时间？</title>
		<answer aid="_" score="0">近一周无自杀想法</answer>
		<answer aid="a" score="1">短暂、一闪即逝</answer>
		<answer aid="b" score="2">较长时间</answer>
		<answer aid="c" score="3">持续或几乎是持续的</answer>
    </question>
	
	<question qid="q7" tag="sD">
		<title>您自杀想法出现的频度如何？</title>
		<answer aid="_" score="0">近一周无自杀想法</answer>
		<answer aid="a" score="1">极少、偶尔</answer>
		<answer aid="b" score="2">有时</answer>
		<answer aid="c" score="3">经常或持续</answer>
    </question>
	
	<question qid="q8" tag="sD">
		<title>您对自杀持什么态度？</title>
		<answer aid="a" score="1">排斥</answer>
		<answer aid="b" score="2">矛盾或无所谓</answer>
		<answer aid="c" score="3">接受</answer>
    </question>
	
	<question qid="q9" tag="sD">
		<title>您觉得自己控制自杀想法、不把它变成行动的能力如何？</title>
		<answer aid="a" score="1">能控制</answer>
		<answer aid="b" score="2">不知能否控制</answer>
		<answer aid="c" score="3">不能控制</answer>
    </question>
	
	<question qid="q10" tag="sD">
		<title>如果出现自杀想法，某些顾虑（如顾及家人、死亡不可逆转等）在多大程度上能阻止您自杀？</title>
		<answer aid="a" score="1">能阻止自杀</answer>
		<answer aid="b" score="2">能减少自杀的危险</answer>
		<answer aid="c" score="3">无顾虑或无影响</answer>
    </question>
	
	<question qid="q11" tag="sD">
		<title>当您想自杀时，主要是为了什么？</title>
		<answer aid="_" score="0">近一周无自杀想法</answer>
		<answer aid="a" score="1">控制形势、寻求关注、报复</answer>
		<answer aid="b" score="2">逃避、减轻痛苦、解决问题</answer>
		<answer aid="e" score="3">前两种情况均有</answer>
    </question>
	
	<question qid="q12" tag="sD">
		<title>您想过结束自己生命的方法了吗？</title>
		<answer aid="a" score="1">没想过</answer>
		<answer aid="b" score="2">想过，但没制订出具体细节</answer>
		<answer aid="c" score="3">制订出具体细节或计划得很周详</answer>
    </question>
	
	<question qid="q13" tag="sD">
		<title>您把自杀想法落实的条件或机会如何？</title>
		<answer aid="_" score="0">近一周无自杀想法</answer>
		<answer aid="a" score="1">没有现成的方法、没有机会</answer>
		<answer aid="b" score="2">需要时间或精力准备自杀工具</answer>
		<answer aid="c" score="3">有现成的方法和机会或预计将来有方法和机会</answer>
    </question>
	
	<question qid="q14" tag="sD">
		<title>您相信自己有能力并且有勇气去自杀吗？</title>
		<answer aid="a" score="1">没有勇气、太软弱、害怕、没有能力</answer>
		<answer aid="b" score="2">不确信自己有无能力、勇气</answer>
		<answer aid="c" score="3">确信自己有能力、有勇气</answer>
    </question>
	
	<question qid="q15" tag="sD">
		<title>您预计某一时间您确实会尝试自杀吗？</title>
		<answer aid="a" score="1">不会</answer>
		<answer aid="b" score="2">不确定</answer>
		<answer aid="c" score="3">会</answer>
    </question>
	
	<question qid="q16" tag="sD">
		<title>为了自杀，您的准备行动完成得怎样？</title>
		<answer aid="a" score="1">没有准备</answer>
		<answer aid="b" score="2">部分完成（如，开始收集药片）</answer>
		<answer aid="c" score="3">全部完成（如，有药片、刀片、有子弹的枪）</answer>
    </question>
	
	<question qid="q17" tag="sD">
		<title>您已着手写自杀遗言了吗？</title>
		<answer aid="a" score="1">没有考虑</answer>
		<answer aid="b" score="2">仅仅考虑、开始但未写完</answer>
		<answer aid="c" score="3">写完</answer>
    </question>
	
	<question qid="q18" tag="sD">
		<title>您是否因为预计要结束自己的生命而抓紧处理一些事情？如买保险或准备遗嘱。</title>
		<answer aid="a" score="1">没有</answer>
		<answer aid="b" score="2">考虑过或做了一些安排</answer>
		<answer aid="c" score="3">有肯定的计划或安排完毕</answer>
    </question>
	
	<question qid="q19" tag="sD">
		<title>您是否让人知道自己的自杀想法？</title>
		<answer aid="_" score="0">近一周无自杀想法</answer>
		<answer aid="a" score="1">坦率主动说出想法</answer>
		<answer aid="b" score="2">不主动说出</answer>
		<answer aid="c" score="3">试图欺骗、隐瞒</answer>
    </question>

  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用于科学研究，非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>
