=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q01_IPsy/Questionnaire.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT questionnaire (description,questions,tags?,remarks?)>

<!ELEMENT description (identifier,caption,information,questionsnum?,interfacetype?)>
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT information (#PCDATA)>
<!ELEMENT questionsnum (#PCDATA)>
<!ELEMENT interfacetype (#PCDATA)>

<!ELEMENT questions (question+)>
<!ELEMENT question (title,answer*)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST question
	qid CDATA #REQUIRED
	tag CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer
	aid CDATA #REQUIRED
	score CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
	name CDATA #REQUIRED
	label CDATA #REQUIRED
>

<!ELEMENT remarks (remark+)>
<!ELEMENT remark (#PCDATA)>
<!ATTLIST remark
	tag CDATA #IMPLIED
	minScore CDATA #REQUIRED
	maxScore CDATA #REQUIRED
>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q07_SCD/SPS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
ds	绝望量表		desperate scale
si	自杀意念		suicide intention
ns	负性自我评价	negative self-assessment
hs	敌意量表		hostility scale

ds(12)	05 12 14 15 17 19 23 28 29 31 33 36
si(8)	04 07 20 21 24 25 30 32
ns(9)	02 06 10 11 18 22 26 27 35
hs(7)	01 03 08 09 13 16 34
-->


<questionnaire>
  <description>
    <identifier>SPS</identifier>
    <caption>自杀可能性量表</caption>
    <information><![CDATA[　　欢迎您填写本量表，以下陈述是用来描述个人感觉和行为的，请仔细阅读每个句子，并选择适合你陈述。请根据您的实际情况进行填写吗，确保填好每个题目。
	【温馨提示】没有反馈信息。
　　本问卷为调查性问卷，我们向您承诺，我们会严格遵守协议，将您的填写结果将只用于科学研究，绝不会以任何形式泄漏您的隐私。请您放心填写真实信息。
　　请您在不受外界打扰的情况下，认真、真实、连续地填写完成本问卷。]]>
	</information>
  </description>

  <questions>

	<question qid="q1" tag="hs">
		<title>我生气时就摔东西</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>

	<question qid="q2" tag="ns">
		<title>我感到很多人关心我</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q3" tag="hs">
		<title>我觉得我容易冲动</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q4" tag="si">
		<title>我的事情糟糕得无法与人分享</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q5" tag="ds">
		<title>我认为自己有太多责任</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q6" tag="ns">
		<title>有许多我能够做也值得做的事情</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q7" tag="si">
		<title>我想自杀以惩罚别人</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q8" tag="hs">
		<title>我感到对别人有敌意</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q9" tag="hs">
		<title>我感到与人们疏离</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q10" tag="ns">
		<title>我感到有人欣赏我</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q11" tag="ns">
		<title>如果我死了许多人会难过</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q12" tag="ds">
		<title>我感到孤独，难以忍受</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q13" tag="hs">
		<title>别人对我有敌意</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q14" tag="ds">
		<title>如果一切可以重来，我的生活会有许多改变</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q15" tag="ds">
		<title>我觉得我有很多事情做不好</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q16" tag="hs">
		<title>我很难找到也难以维持自己喜欢的工作</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q17" tag="ds">
		<title>我认为如果我死了没人会想念我</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q18" tag="ns">
		<title>我的事情都进展顺利</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q19" tag="ds">
		<title>我觉得人们对我期望太高</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q20" tag="si">
		<title>我觉得我需要为自己的所做所为而自我惩罚</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q21" tag="si">
		<title>我觉得这个世界不值得我继续活下去</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q22" tag="ns">
		<title>我很仔细地计划未来</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q23" tag="ds">
		<title>我觉得我没有太多可以依靠的朋友</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q24" tag="si">
		<title>如果我死了别人会过得更好一些</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q25" tag="si">
		<title>我觉得就这样活着太痛苦了，还不如死掉</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q26" tag="ns">
		<title>我觉得(或曾经觉得)与母亲关系亲近</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q27" tag="ns">
		<title>我觉得(或曾经觉得)与同伴关系亲近</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q28" tag="ds">
		<title>我感到绝望，我的事情不可能好起来</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q29" tag="ds">
		<title>我感到别人不赞成我和我的所作所为</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q30" tag="si">
		<title>我想过怎样弄死自己</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q31" tag="ds">
		<title>我有经济压力</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q32" tag="si">
		<title>我想自杀</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q33" tag="ds">
		<title>我感到疲乏和无精打采</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q34" tag="hs">
		<title>我生气时就砸东西</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q35" tag="ns">
		<title>我觉得(或曾经觉得)与父亲关系亲近</title>
		<answer aid="a" score="4">从来没有</answer>
		<answer aid="b" score="3">偶尔</answer>
		<answer aid="c" score="2">大部分时间</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q36" tag="ds">
		<title>我无论在哪儿都无法感到快乐</title>
		<answer aid="a" score="1">从来没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">大部分时间</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用于科学研究，非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q02_2K/Q2_InternetAddiction.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	网络成瘾量表（原问卷共有20道题目）；
	插入了7道测谎题和自我粉饰题，用tag=M和tag=E标出。
-->

<questionnaire>
  <description>
    <identifier>Q2_NetAddiction</identifier>
    <caption>互联网使用行为习惯调查问卷</caption>
    <information><![CDATA[　　欢迎您填写本问卷，后面的题目列出了与您使用互联网的行为习惯相关的一些问题，对每项描述，请指出您具有哪种感受的频度，选择您认同的选项。

　　请您在不受外界打扰的情况下，认真、真实地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
		<title>你会发现上网的时间超过原先预计的时间吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
  
    <question qid="q2">
		<title>你会因为上网忽略自己要做的事情吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q3">
		<title>你更愿意上网而不是和亲密的朋友呆在一起吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q4">
		<title>你经常在网上结交新朋友吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="M148" tag="M">
		<title>当我正在做一件重要事情的时候，如果有人向我请教或打扰我，我会不耐烦的。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q5">
		<title>生活中，朋友、家人会抱怨你上网时间太长吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="M383" tag="M">
		<title>我喜欢人多热闹的场合</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q6">
		<title>你因为上网影响学习了吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q7">
		<title>你是否会不顾身边需要解决的一些问题，而上网查看E-mail或留言？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q8">
		<title>你因为上网影响到你的日常生活了吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>

	<question qid="q9">
		<title>当有人问你上网做些什么时，你会有所防范或隐瞒吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
	</question>
	
	<question qid="E52" tag="E">
		<title>在游戏或打牌时你曾经作弊吗？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>


	<question qid="q10">
		<title>你会因为心情不好去上网吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q11">
		<title>你在一次上网后会渴望下一次上网吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q12">
		<title>如果无法上网你会觉得生活空虚无聊吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q13">
		<title>你会因为别人打搅你上网而发脾气吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="M30" tag="M">
		<title>有时我真想骂人。</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q14">
		<title>你会上网到深夜不去睡觉吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q15">
		<title>你在离开网络后会想着网上的事情吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
	</question>
	
	<question qid="q16">
		<title>你在上网时会对自己说：“就再玩一会儿”吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q17">
		<title>你曾尝试减少上网时间而最终失败吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="E71" tag="E">
		<title>你去赴约会或上班时，曾否迟到？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q18">
		<title>你会对人隐瞒你上网多长时间吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="q19">
		<title>你宁愿上网而不愿意和朋友们出去玩吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="M397" tag="M">
		<title>我喜欢聚会和社交活动</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q20">
		<title>你会因为不能上网变得烦躁不安，喜怒无常吗？</title>
		<answer aid="a" score="1">几乎没有</answer>
		<answer aid="b" score="2">偶尔</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">经常</answer>
		<answer aid="e" score="5">总是</answer>
    </question>
	
	<question qid="M234" tag="M">
		<title>我很容易生气，但很快就平静下来</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

  </questions>

  <remarks>
    <remark minScore="min" maxScore="max">非常感谢您填写我们的问卷！您填写的信息将仅用于科学研究。</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/models/quiz/quiz/Q07_SCD/SDS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
心理焦虑状况测量量表
-->

<questionnaire>
  <description>
    <identifier>SDS</identifier>
    <caption>抑郁自评量表</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是针对抑郁评价而设计的。通过填写本量表，您可以评测您的焦虑状况。
　　下面有二十条文字，请仔细阅读每一条，把意思弄明白，然后根据您最近一星期的实际感受，选择与您的感受最相符的选项。

　　请您注意，下面这个测试是根据您【一周内的】情绪体验、实践活动回答：
　　　　1.没有或很少时间(过去一周内，出现这类情况的日子不超过1天)；
　　　　2.小部分时间(过去一周内，有1-2天有过这类情况)；
　　　　3.相当多时间(过去一周内，3-4天有过这类情况）；
　　　　4.绝大部分或全部时间(过去一周内，有5-7天有过这类情况)。

　　本问卷为调查性问卷，我们向您承诺，我们会严格遵守协议，将您的填写结果将只用于科学研究，绝不会以任何形式泄漏您的隐私。请您放心填写真实信息。
　　请您在不受外界打扰的情况下，认真、真实、连续地填写完成本问卷。
	]]>
	</information>
  </description>

  <questions>
    <question qid="q01" tag="D">
      <title>最近一星期以来，我感到情绪沮丧，郁闷</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q02" tag="D">
      <title>最近一星期以来，我感到早晨心情最好</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q03" tag="D">
      <title>最近一星期以来，我要哭或想哭</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q04" tag="D">
      <title>最近一星期以来，我夜间睡眠不好</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q05" tag="D">
      <title>最近一星期以来，我吃饭象平时一样多</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q06" tag="D">
      <title>最近一星期以来，我的性功能正常</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q07" tag="D">
      <title>最近一星期以来，我感到体重减轻</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q08" tag="D">
      <title>最近一星期以来，我为便秘烦恼</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q09" tag="D">
      <title>最近一星期以来，我的心跳比平时快</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q10" tag="D">
      <title>最近一星期以来，我无故感到疲劳</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q11" tag="D">
      <title>最近一星期以来，我的头脑象往常一样清楚</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q12" tag="D">
      <title>最近一星期以来，我做事情象平时一样不感到困难</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q13" tag="D">
      <title>最近一星期以来，我坐卧不安，难以保持平静</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q14" tag="D">
      <title>最近一星期以来，我对未来感到有希望</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q15" tag="D">
      <title>最近一星期以来，我比平时更容易激怒</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q16" tag="D">
      <title>最近一星期以来，我觉得决定什么事很容易</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q17" tag="D">
      <title>最近一星期以来，我感到自已是有用的和不可缺少的人</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q18" tag="D">
      <title>最近一星期以来，我的生活很有意义</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>

    <question qid="q19" tag="D">
      <title>最近一星期以来，假若我死了别人会过得更好</title>
      <answer aid="a1" score="0">没有或很少时间</answer>
      <answer aid="a2" score="1">少部分时间</answer>
      <answer aid="a3" score="2">相当多时间</answer>
      <answer aid="a4" score="3">绝大部分或全部时间</answer>
    </question>

    <question qid="q20" tag="D">
      <title>最近一星期以来，我仍旧喜爱自己平时喜爱的东西</title>
      <answer aid="a1" score="3">没有或很少时间</answer>
      <answer aid="a2" score="2">少部分时间</answer>
      <answer aid="a3" score="1">相当多时间</answer>
      <answer aid="a4" score="0">绝大部分或全部时间</answer>
    </question>
  </questions>
  
   <tags>
	<tag name="A" label="心理抑郁"><![CDATA[本问卷对您的焦虑状况进行了测评。]]>
	</tag>
   </tags>
   
   <remarks>
    <remark tag="D" minScore="min" maxScore="20">你的分数处于低水平范围：根据问卷的得分显示，你在此刻并没有或只有很少的抑郁症状，并没有深陷于抑郁情绪的困扰。如果你觉得自己可能已经陷入了抑郁情绪状态，那么建议你立刻去求助于专业的心理咨询人员。</remark>
    <remark tag="D" minScore="20" maxScore="40">你的分数处于中等水平范围：你可能有轻微或轻度抑郁情绪问题。建议你寻求专业性的建议与指导，从而帮助你提高自身的情绪应对能力并在未来免遭类似的消极情绪困扰。</remark>
    <remark tag="D" minScore="40" maxScore="max">你的分数处于高水平范围：这说明在你身上具有比其他人更多的抑郁症状。你可能比较容易遭到抑郁情绪的侵袭。我们建议你去向专业的心理咨询或治疗人员寻求帮助，从而彻底检查自己的心理健康状态。</remark>
   </remarks>

</questionnaire>
