=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q02_2K/Questionnaire.dtd
<?xml version="1.0" encoding="utf-8"?>
        <!ELEMENT questionnaire (description,questions,tags?,remarks?)>

        <!ELEMENT description (identifier,caption,information,questionsnum?,interfacetype?)>
        <!ELEMENT identifier (#PCDATA)>
        <!ELEMENT caption (#PCDATA)>
        <!ELEMENT information (#PCDATA)>
        <!ELEMENT questionsnum (#PCDATA)>
        <!ELEMENT interfacetype (#PCDATA)>

        <!ELEMENT questions (question+)>
        <!ELEMENT question (title,restriction?,answer*)>
        <!ELEMENT title (#PCDATA)>
        <!ATTLIST question
                qid CDATA #REQUIRED
                tag CDATA #IMPLIED
                type (single|multi|textarea|text|number|range|color|date|time|email) "single"
                >

        <!ELEMENT restriction EMPTY>
        <!ATTLIST restriction
                placeholder CDATA #IMPLIED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                pattern CDATA #IMPLIED
                size    CDATA #IMPLIED
                step    CDATA #IMPLIED
                >

        <!ELEMENT answer (#PCDATA)>
        <!ATTLIST answer
                aid CDATA #REQUIRED
                score CDATA #IMPLIED
                type CDATA #IMPLIED
                >

        <!ELEMENT tags (tag+)>
        <!ELEMENT tag (#PCDATA)>
        <!ATTLIST tag
                name CDATA #REQUIRED
                label CDATA #REQUIRED
                >

        <!ELEMENT remarks (remark+)>
        <!ELEMENT remark (#PCDATA)>
        <!ATTLIST remark
                tag CDATA #IMPLIED
                minScore CDATA #REQUIRED
                maxScore CDATA #REQUIRED
                >

=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q05_Sina/SINA_Demo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<questionnaire>
  <description>
    <identifier>SINA_Demo</identifier>
    <caption>个人及家庭基本情况调查</caption>
    <information><![CDATA[　　欢迎您填写本量表，后面的题目列出与您的基本信息相关的问题一些问题，对每项描述，请根据您的实际情况进行填写。
	【温馨提示】没有反馈信息。
　　本问卷为调查性问卷，我们向您承诺，我们会严格遵守协议，将您的填写结果将只用于科学研究，绝不会以任何形式泄漏您的隐私。请您放心填写真实信息。
　　请您在不受外界打扰的情况下，认真、真实、连续地填写完成本问卷。]]>
	</information>
  </description>

  <questions>

	<question qid="q1" type="text">
		<title>您的年龄(请填写数字，例如25；请真实填写，此题目将作为甄别填写是否有效的信息)：</title>
    </question>

	<question qid="q2">
		<title>您的性别：</title>
		<answer aid="m" score="0">男性</answer>
		<answer aid="f" score="0">女性</answer>
    </question>

	<question qid="q3" type="text">
		<title>您的民族（请具体填写，例如，汉族，回族等）：</title>
    </question>
	
	<question qid="q4">
		<title>是否为独生子女：</title>
		<answer aid="y" score="0">是</answer>
		<answer aid="n" score="0">否</answer>
    </question>

	<question qid="q5">
		<title>您的文化程度</title>
		<answer aid="a" score="1">小学及以下（或在读）</answer>
		<answer aid="b" score="2">初中（或在读）</answer>
		<answer aid="c" score="3">高中（或在读）</answer>
		<answer aid="d" score="4">中专（或在读）</answer>
		<answer aid="e" score="5">本科（或在读）</answer>
		<answer aid="f" score="6">大转（或在读）</answer>
		<answer aid="g" score="7">硕士（或在读）</answer>
		<answer aid="h" score="8">博士（或在读）</answer>
    </question>

	<question qid="q6">
		<title>个人婚姻状况：</title>
		<answer aid="a" score="0">已婚</answer>
		<answer aid="b" score="0">恋爱</answer>
		<answer aid="c" score="0">（婚后）分居</answer>
		<answer aid="d" score="0">离异</answer>
		<answer aid="e" score="0">丧偶</answer>
		<answer aid="f" score="0">（未婚）单身</answer>
    </question>

	<question qid="q7">
		<title>是否生育子女：</title>
		<answer aid="a" score="0">是</answer>
		<answer aid="b" score="0">否</answer>
    </question>	
	
	<question qid="q8">
		<title>您的职业：</title>
		<answer aid="a" score="0">工人</answer>
		<answer aid="b" score="0">农民</answer>
		<answer aid="c" score="0">公务员</answer>
		<answer aid="d" score="0">医生/护士</answer>
		<answer aid="e" score="0">职员</answer>
		<answer aid="f" score="0">媒体从业人员</answer>
		<answer aid="g" score="0">学生</answer>
		<answer aid="h" score="0">科研人员/教师</answer>
		<answer aid="i" score="0">军人武警</answer>
		<answer aid="j" score="0">自主经营者</answer>
		<answer aid="k" score="0">自由职业者</answer>
		<answer aid="l" score="0">失业人群</answer>
		<answer aid="m" score="0">其他</answer>
    </question>

	<question qid="q9">
		<title>家庭人均月收入：</title>
		<answer aid="a" score="0">2千元以下</answer>
		<answer aid="b" score="0">2千—4千元</answer>
		<answer aid="c" score="0">4千—6千元</answer>
		<answer aid="d" score="0">6千—8千元</answer>
		<answer aid="e" score="0">8千—1万元</answer>
		<answer aid="f" score="0">1万元以上</answer>
	</question>

  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用于科学研究，非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q04_GD/Soc0_Demographic.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<questionnaire>
  <description>
    <identifier>Soc_Demo</identifier>
    <caption>个人及家庭基本情况调查</caption>
    <information><![CDATA[　　欢迎您填写本量表，后面的题目列出与您的基本信息相关的问题一些问题，对每项描述，请根据您的实际情况进行填写。
	
　　我们向您承诺，我们会严格遵守协议，将您的填写结果将只用于科学研究，绝不会以任何形式泄漏您的隐私。请您放心填写真实信息。
　　请您在不受外界打扰的情况下，认真、真实、连续地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
		<title>您的性别：</title>
		<answer aid="m" score="0">男性</answer>
		<answer aid="f" score="0">女性</answer>
    </question>

	<question qid="q2" type="text">
		<title>您的年龄(请填写数字，例如25；请真实填写，此题目将作为甄别填写是否有效的信息)：</title>
    </question>

	<question qid="q3" type="text">
		<title>您家有几口人(请填写数字，例如4；请真实填写，此题目将作为甄别填写是否有效的信息)：</title>
    </question>
	
	<question qid="q4">
		<title>您的政治面貌：</title>
		<answer aid="a" score="0">无党派</answer>
		<answer aid="b" score="0">共青团员</answer>
		<answer aid="c" score="0">中共党员</answer>
		<answer aid="d" score="0">民主党派</answer>
    </question>
	
	<question qid="q5">
		<title>您的户口是：</title>
		<answer aid="a" score="0">非农业户口</answer>
		<answer aid="b" score="0">农业户口</answer>
    </question>

	<question qid="q6">
		<title>您现在居住的地区是：</title>
		<answer aid="a" score="0">直辖市</answer>
		<answer aid="b" score="0">省会城市</answer>
		<answer aid="c" score="0">中小城市</answer>
		<answer aid="d" score="0">城镇</answer>
		<answer aid="e" score="0">农村</answer>
    </question>

	<question qid="q7">
		<title>您在外地工作的经历如何：</title>
		<answer aid="a" score="0">经常在外地工作</answer>
		<answer aid="b" score="0">偶尔在外地工作</answer>
		<answer aid="c" score="0">几乎不在外地工作</answer>
    </question>
	
	<question qid="q8">
		<title>您家是否有正在上学的孩子？（如果有的话，请填写年级。）</title>
		<answer aid="a" score="0">没有</answer>
		<answer aid="b" type="text" score="0">有，正在上几年级？（填写年级）</answer>
    </question>
	
	<question qid="q9" type="text">
		<title>您的民族（请具体填写，例如，汉族，回族等）：</title>
    </question>
	
	<question qid="q10">
		<title>您的职业（如果没有固定职业，就以从事时间较长的为主）：</title>
		<answer aid="a" score="0">在家务农</answer>
		<answer aid="b" score="0">企业职工</answer>
		<answer aid="c" score="0">事业单位人员</answer>
		<answer aid="d" score="0">党政机关人员</answer>
		<answer aid="e" score="0">个体经营</answer>
		<answer aid="f" score="0">外出打工</answer>
		<answer aid="g" score="0">离退休</answer>
		<answer aid="h" score="0">无职业/失业</answer>
		<answer aid="i" score="0">自由职业</answer>
		<answer aid="j" score="0">学生</answer>
		<answer aid="k" score="0" type="text">其他职业（请具体说明）</answer>
    </question>
	
	<question qid="q11">
		<title>您的教育程度</title>
		<answer aid="a" score="1">不识字</answer>
		<answer aid="b" score="1">小学（或在读）</answer>
		<answer aid="c" score="2">初中（或在读）</answer>
		<answer aid="d" score="3">高中（或在读）</answer>
		<answer aid="e" score="4">中专（或在读）</answer>
		<answer aid="f" score="5">大学专科（或在读）</answer>
		<answer aid="g" score="6">大学本科（或在读）</answer>
		<answer aid="h" score="7">硕士研究生（或在读）</answer>
		<answer aid="i" score="8">博士研究生（或在读）</answer>
    </question>
	
	<question qid="q12">
		<title>您信奉什么宗教：</title>
		<answer aid="a" score="0">不信</answer>
		<answer aid="b" score="0">佛教</answer>
		<answer aid="c" score="0">道教</answer>
		<answer aid="d" score="0">基督教（天主教、新教、东正教）</answer>
		<answer aid="e" score="0">伊斯兰教</answer>
		<answer aid="f" score="0" type="text">其他宗教（请具体填写）</answer>
    </question>

	<question qid="q13">
		<title>您每天在电视、报刊或网络上关注时事新闻的平均时间大约为：</title>
		<answer aid="a" score="0">从来不看</answer>
		<answer aid="b" score="0">看少于15分钟</answer>
		<answer aid="c" score="0">15~30分钟</answer>
		<answer aid="d" score="0">30~45分钟</answer>
		<answer aid="e" score="0">45~60分钟</answer>
		<answer aid="f" score="0">一小时以上</answer>
	</question>

	<question qid="q14" type="text">
		<title>您家去年一年的现金收入约为多少元？（请精确到百元，例如：45800元）</title>
    </question>
	
	<question qid="q15" type="text">
		<title>您家去年大约将收入的百分之多少存入银行？（填写百分比，例如：30%）：</title>
    </question>
	
	<question qid="q16" type="text">
		<title>政府税收主要用于本地县（市）政府行政部门的必要开支和当地公共基础设施建设，您认为税收应占个人收入的百分比为多少？（填写百分比，例如：30%）：</title>
    </question>
	
	<question qid="q17" type="text">
		<title>如果现在想在您家周围再建或再买一套与目前住房面积同样大小的住房，其总价相当于您家一年现金收入的几倍（填写数字，例如10就表示十倍）：</title>
    </question>
	
	<question qid="q18" type="text">
		<title>您家去年一年的各种开支合计约为多少元？（精确到百元，例如：31500元）</title>
    </question>
	
	<question qid="q19" type="text">
		<title>在您家去年一年的各种开支当中，大约有开支的【百分之多少】用于吃饭（粮食，蔬菜，肉蛋奶，油盐酱醋等）？（填写百分比，例如：30%）：</title>
    </question>
	
	<question qid="q20" type="text">
		<title>在您家去年一年的各种开支当中，大约有开支的【百分之多少】用于教育？（填写百分比，例如：30%）：</title>
    </question>
	
	<question qid="q21" type="text">
		<title>在您家去年一年的各种开支当中，大约有开支的【百分之多少】用于看病就医？（填写百分比，例如：8%）：</title>
    </question>

  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用于科学研究，非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q01_IPsy/P4_BasicInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	此问卷由心理所提供，源问卷参见Word文件《第四部分 基本信息》。
-->

<questionnaire>
  <description>
    <identifier>Q1_Deomographic</identifier>
    <caption>微博使用情况测试量表</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是为了了解微博用户群的基本信息而设计的。
您的填写结果将作科研之用，我们确保为您保密！]]>
	</information>
  </description>

  <questions>
	<question qid="sex">
      <title>您的性别：</title>
      <answer aid="m" score="0">男性</answer>
      <answer aid="f" score="0">女性</answer>
    </question>

    <question qid="age">
      <title>您的年龄段：</title>
      <answer aid="l18" score="1">18岁以下</answer>
      <answer aid="l20" score="2">18~20岁</answer>
      <answer aid="l25" score="3">21~25岁</answer>
      <answer aid="l30" score="4">26~30岁</answer>
	  <answer aid="l35" score="5">31~35岁</answer>
	  <answer aid="l40" score="6">36~40岁</answer>
	  <answer aid="l45" score="7">41~45岁</answer>
	  <answer aid="l50" score="8">46~50岁</answer>
	  <answer aid="g50" score="9">50岁以上</answer>
    </question>
	
	<question qid="edu">
      <title>您的学历：</title>
      <answer aid="pr" score="1">小学及以下</answer>
      <answer aid="md" score="2">初中</answer>
      <answer aid="hi" score="3">高中</answer>
	  <answer aid="zz" score="4">中专</answer>
	  <answer aid="dz" score="5">大专</answer>
      <answer aid="ug" score="6">大学本科</answer>
	  <answer aid="ms" score="7">硕士研究生</answer>
	  <answer aid="dr" score="8">博士研究生</answer>
    </question>
	
	<question qid="job">
      <title>您的职业：</title>
      <answer aid="wk" score="1">工人</answer>
      <answer aid="fm" score="2">农民</answer>
      <answer aid="of" score="3">公务员</answer>
	  <answer aid="dr" score="4">医生/护士</answer>
	  <answer aid="ck" score="5">职员</answer>
      <answer aid="md" score="6">媒体从业人员</answer>
	  <answer aid="st" score="7">学生</answer>
	  <answer aid="rs" score="8">科研人员/教师</answer>
	  <answer aid="so" score="9">军人/武警</answer>
	  <answer aid="bu" score="10">自主经营者</answer>
	  <answer aid="fr" score="11">自由职业者</answer>
	  <answer aid="no" score="12">失业人群</answer>
	  <answer aid="ot" score="13">其他</answer>
    </question>

    <question qid="mn">
      <title>您每月个人可自由支配的钱数为：</title>
      <answer aid="l5h" score="1">500元以下</answer>
      <answer aid="l1k" score="2">500—1000元</answer>
      <answer aid="l2k" score="3">1000—2000元</answer>
      <answer aid="l5k" score="4">2000—5000元</answer>
	  <answer aid="g5k" score="5">5000元以上</answer>
    </question>
    
	<question qid="grw">
      <title>您成长所在地为：</title>
      <answer aid="c1" score="1">直辖市及省会</answer>
      <answer aid="c2" score="2">一般城市</answer>
	  <answer aid="to" score="3">城镇</answer>
      <answer aid="vi" score="4">农村</answer>
    </question>
	
    <question qid="liv">
      <title>您目前工作（学习）所在地为：</title>
      <answer aid="c1" score="1">直辖市及省会</answer>
      <answer aid="c2" score="2">一般城市</answer>
	  <answer aid="to" score="3">城镇</answer>
      <answer aid="vi" score="4">农村</answer>
    </question>

    <question qid="livT">
      <title>您目前工作（学习）所在地居住时间为：</title>
      <answer aid="l1" score="1">1年及以下</answer>
      <answer aid="l3" score="2">1-3年</answer>
      <answer aid="l5" score="3">3-5年</answer>
      <answer aid="l10" score="4">5-10年</answer>
      <answer aid="g10" score="5">大于10年</answer>
    </question>

  </questions>

  
  <tags>
	<tag name="" label="致谢"><![CDATA[非常感谢您填写我们的问卷调查！]]></tag>
  </tags>

  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用作科学研究。</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q02_2K/Q2_Loneliness.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	孤独感测试问卷（原问卷共有20道题目）；
	插入了6道测谎题和自我粉饰题，用tag=M和tag=E标出。
-->

<questionnaire>
  <description>
    <identifier>Q2_UCLAAl</identifier>
    <caption>孤独感调查问卷</caption>
    <information><![CDATA[　　欢迎您填写本问卷，下面的题目列出了人们在使用微博的过程中有时出现的一些感受，对每项描述，请指出您在使用微博时具有哪种感受的频度，选择您认同的选项。

　　请您在不受外界打扰的情况下，认真、真实地填写完成本问卷。]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
		<title>你常感到与周围人的关系和谐吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
  
    <question qid="q2">
		<title>你常感到缺少伙伴吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q3">
		<title>你常感到没人可以信赖吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q4">
		<title>你常感到寂寞吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
		
	<question qid="M142" tag="M">
		<title>有时我觉得我真是毫无用处。</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>
	
	<question qid="q5">
		<title>你常感到自己是属于朋友们中的一员吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q6">
		<title>你常感到与周围的人有很多共同点吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
		
	<question qid="M267" tag="E">
		<title>人多的时候，我不知道说些什么话好</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q7">
		<title>你常感到与任何人都不亲密了吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q8">
		<title>你常感到你的兴趣与想法和周围的人不一样吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>

	<question qid="q9">
		<title>你常感到想要与人来往、结交朋友吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
	</question>

	<question qid="q10">
		<title>你常感到与人亲近吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="E39" tag="E">
		<title>你有时有点自吹自擂吗？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>

	<question qid="q11">
		<title>你常感到被人冷落吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q12">
		<title>你常感到你与别人来往毫无意义吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q13">
		<title>你常感到没有人很了解你吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="M170" tag="M">
		<title>我不在乎别人对我有什么看法</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>
	
	<question qid="q14">
		<title>你常感到与别人隔开了吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q15">
		<title>你常感到当你愿意时就能找到伙伴吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
	</question>
	
	<question qid="q16">
		<title>你常感到有人真正了解你吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="q17">
		<title>你常感到羞怯吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>

	<question qid="E79" tag="E">
		<title>若你犯有错误，是否都愿意承认？</title>
		<answer aid="a" score="1">是的</answer>
		<answer aid="b" score="0">不是</answer>
    </question>

	<question qid="q18">
		<title>你常感到人们围着你但并不关心你吗？</title>
		<answer aid="a" score="1">从不</answer>
		<answer aid="b" score="2">很少</answer>
		<answer aid="c" score="3">有时</answer>
		<answer aid="d" score="4">一直</answer>
    </question>
	
	<question qid="q19">
		<title>你常感到有人愿意与你交谈吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
	<question qid="E25" tag="E">
		<title>你是否有时候谈论一些你毫无所知的事情？</title>
		<answer aid="a" score="0">是的</answer>
		<answer aid="b" score="1">不是</answer>
    </question>
	
	<question qid="q20">
		<title>你常感到有人值得你信赖吗？</title>
		<answer aid="a" score="4">从不</answer>
		<answer aid="b" score="3">很少</answer>
		<answer aid="c" score="2">有时</answer>
		<answer aid="d" score="1">一直</answer>
    </question>
	
  </questions>
  
  <remarks>
    <remark minScore="min" maxScore="max">非常感谢您填写我们的问卷！</remark>
  </remarks>

</questionnaire>

=== Yufang0828/PsyMap/PsyMap/util/quiz/quiz/Q01_IPsy/P1_UsingCyber.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questionnaire SYSTEM "Questionnaire.dtd">

<!--
	此问卷由心理所提供，问题参见Word文档《第一部分 网络及微博使用情况》。
-->

<questionnaire>
  <description>
    <identifier>Q1_Cyber</identifier>
    <caption>网络及微博使用情况</caption>
    <information><![CDATA[欢迎您填写本量表，本量表是针对微博使用行为动机调查而设计的。
您填写的信息结果将用于我们进行科学研究，十分感谢您的合作！]]>
	</information>
  </description>

  <questions>
	<question qid="q1">
      <title>您接触网络有多长时间：</title>
      <answer aid="l1" score="0">少于1年</answer>
      <answer aid="l3" score="2">2-3年</answer>
	  <answer aid="l5" score="4">3-5年</answer>
	  <answer aid="l10" score="6">5-10年</answer>
	  <answer aid="g10" score="8">10年以上</answer>
    </question>
  
    <question qid="q2">
      <title>目前，你使用网络的频率是</title>
      <answer aid="a" score="0">有事情时，偶尔使用</answer>
      <answer aid="b" score="2">每天使用2小时以下</answer>
	  <answer aid="c" score="4">每天使用2-4小时</answer>
	  <answer aid="d" score="6">每天使用4-8小时</answer>
	  <answer aid="e" score="8">每天使用8小时以上</answer>
    </question>
	
	<question qid="q3" type="multi">
      <title>目前，你使用网络的哪几项功能？(可多选)</title>
      <answer aid="a" score="1">听音乐</answer>
      <answer aid="b" score="1">看视频</answer>
	  <answer aid="c" score="1">阅读各类新闻</answer>
	  <answer aid="d" score="1">查找信息</answer>
	  <answer aid="e" score="1">分享信息</answer>
	  <answer aid="f" score="1">人际交往（聊天BBS、论坛、Email等）</answer>
	  <answer aid="g" score="1">购物</answer>
	  <answer aid="h" score="1">学习</answer>
	  <answer aid="i" score="1">在线游戏</answer>
	  <answer aid="j"  score="1" type="text">其他(请具体列出:)</answer>
    </question>
	
	<question qid="q4">
      <title>目前，你使用新浪微博的频率是</title>
      <answer aid="a" score="0">几乎不使用</answer>
      <answer aid="b" score="1">偶尔使用</answer>
	  <answer aid="c" score="2">每周几次</answer>
	  <answer aid="d" score="4">每天使用几次</answer>
	  <answer aid="e" score="8">随时在线</answer>
    </question>
	
	<question qid="q5">
      <title>目前，你觉得你每天花在新浪微博上的时间是</title>
      <answer aid="a" score="0">少于15分钟</answer>
      <answer aid="b" score="1">15-30分钟</answer>
	  <answer aid="c" score="2">30分钟-1个小时</answer>
	  <answer aid="d" score="3">1-2个小时</answer>
	  <answer aid="e" score="4">多于2个小时</answer>
    </question>
	
	<question qid="q6" type="multi">
      <title>你是如何开始使用新浪微博？(可多选)</title>
      <answer aid="a" score="1">朋友推荐</answer>
      <answer aid="b" score="1">看到周围人使用</answer>
	  <answer aid="c" score="1">网络媒体宣传</answer>
	  <answer aid="d" score="1">为了关注某个人（组织、群体）</answer>
	  <answer aid="e" score="1">自身需求</answer>
	  <answer aid="f" score="1">特定原因（例如公司要求使用）</answer>
	  <answer aid="g" score="1">其他</answer>
    </question>
	
	<question qid="q7">
      <title>在你关注的人中，有多少是你熟悉认识的人</title>
      <answer aid="a" score="0">0-50个</answer>
      <answer aid="b" score="1">50-100个</answer>
	  <answer aid="c" score="2">100-200个</answer>
	  <answer aid="d" score="4">200-500个</answer>
	  <answer aid="e" score="8">500以上</answer>
    </question>
	
	<question qid="q8">
      <title>在你的粉丝中，有多少是你熟悉认识的人</title>
	  <answer aid="a" score="0">0-50个</answer>
      <answer aid="b" score="1">50-100个</answer>
	  <answer aid="c" score="2">100-200个</answer>
	  <answer aid="d" score="4">200-500个</answer>
	  <answer aid="e" score="8">500以上</answer>
    </question>

	<question qid="q9" type="multi">
      <title>你关注的个人主页有以下哪些类型？（可多选；选项较多，请您拖动右侧的滚动条查看所有内容）</title>
	  <answer aid="a" score="1">娱乐</answer>
	  <answer aid="b" score="1">体育</answer>
	  <answer aid="c" score="1">时尚</answer>
	  <answer aid="d" score="1">生活</answer>
	  <answer aid="e" score="1">财经</answer>
	  <answer aid="f" score="1">文学出版</answer>
	  <answer aid="g" score="1">传媒</answer>
	  <answer aid="h" score="1">旅游</answer>
	  <answer aid="i" score="1">游戏</answer>
	  <answer aid="j" score="1">动漫</answer>
	  <answer aid="k" score="1">微博之星</answer>
	  <answer aid="l" score="1">校园</answer>
	  <answer aid="m" score="1">公益人士</answer>
	  <answer aid="n" score="1">两会代表</answer>
	  <answer aid="o" score="1">农业</answer>
	  <answer aid="p" score="1">政府官员</answer>
	  <answer aid="q" score="1">房产</answer>
	  <answer aid="r" score="1">军事航空</answer>
	  <answer aid="s" score="1">育儿</answer>
	  <answer aid="t" score="1">广告公关</answer>
	  <answer aid="u" score="1">科普</answer>
	  <answer aid="v" score="1">汽车</answer>
	  <answer aid="w" score="1">人体艺术</answer>
	  <answer aid="x" score="1">IT</answer>
	  <answer aid="y" score="1">自己朋友</answer>
    </question>

	<question qid="q10" type="multi">
      <title>以下哪种方式是你最经常使用新浪微博的方式(可多选)</title>
      <answer aid="a" score="1">网页版</answer>
      <answer aid="b" score="1">电脑桌面版</answer>
	  <answer aid="c" score="1">移动终端版</answer>
	  <answer aid="d"  score="1" type="text">其他(请具体列出:)</answer>
    </question>
	
	<question qid="q11">
      <title>每周参与新浪微博投票的次数大概是</title>
      <answer aid="a" score="0">0次，从不参与</answer>
      <answer aid="b" score="1">1-3次，比较少参与</answer>
	  <answer aid="c" score="2">4-6次，比较积极的参与</answer>
	  <answer aid="d" score="3">7次以上，非常热衷的参与</answer>
    </question>
	
	<question qid="q12">
      <title>你平均每天@别人的频率大概是</title>
      <answer aid="a" score="0">0次，不了解这个功能</answer>
      <answer aid="b" score="1">1-3次，有，但不太多</answer>
	  <answer aid="c" score="2">4-9次，还算不少</answer>
	  <answer aid="d" score="4">10次及以上，非常多</answer>
    </question>
	
	<question qid="q13" type="multi">
      <title>以下新浪微博功能你使用过哪几个（可多选；选项较多，请您拖动右侧的滚动条查看所有内容）</title>
	  <answer aid="a" score="1">名人堂</answer>
	  <answer aid="b" score="1">微博达人</answer>
	  <answer aid="c" score="1">风云榜</answer>
	  <answer aid="d" score="1">微话题</answer>
	  <answer aid="e" score="1">微博精选</answer>
	  <answer aid="f" score="1">随便看看</answer>
	  <answer aid="g" score="1">同城微博</answer>
	  <answer aid="h" score="1">微访谈</answer>
	  <answer aid="i" score="1">微直播</answer>
	  <answer aid="j" score="1">大屏幕</answer>
	  <answer aid="k" score="1">热门微博</answer>
	  <answer aid="l" score="1">微电台</answer>
	  <answer aid="m" score="1" type="text">其他（请详细列出:）</answer>
    </question>
	
	<question qid="q14" type="multi">
		<title>在你的新浪微博上，你关注了哪类微群(可多选)</title>
		<answer aid="a" score="1">明星粉丝</answer>
		<answer aid="b" score="1">兴趣爱好</answer>
		<answer aid="c" score="1">同城生活</answer>
		<answer aid="d" score="1">行业交流</answer>
		<answer aid="e" score="1">同学校园</answer>
    </question>
	
	<question qid="q15" type="multi">
		<title>下列关于兴趣爱好的微群中，你会关注哪类（可多选；选项较多，请您拖动右侧的滚动条查看所有内容）</title>
		<answer aid="a" score="1">囧笑话</answer>
		<answer aid="b" score="1">动漫</answer>
		<answer aid="c" score="1">游戏</answer>
		<answer aid="d" score="1">体育</answer>
		<answer aid="e" score="1">购物</answer>
		<answer aid="f" score="1">旅游</answer>
		<answer aid="g" score="1">摄影</answer>
		<answer aid="h" score="1">音乐</answer>
		<answer aid="i" score="1">电影</answer>
		<answer aid="j" score="1">电视</answer>
		<answer aid="k" score="1">数码</answer>
		<answer aid="l" score="1">稀奇古怪</answer>
    </question>
	
	<question qid="q16" type="multi">
		<title>在新浪微博应用中，你使用了哪类应用(可多选)</title>
		<answer aid="a" score="1">娱乐类（星座运势、相册、游戏等）</answer>
		<answer aid="b" score="1">生活类（日程、购物、天气、旅游、美食、健康等）</answer>
		<answer aid="c" score="1">社交类（好友互动、社区交友、聊天、婚配等）</answer>
		<answer aid="d" score="1">资讯类（新闻、杂志等）</answer>
		<answer aid="e" score="1">工具类（粉丝管理、提醒管理、关注管理、RSS订阅等）</answer>
    </question>
	
	<question qid="q17" type="multi">
      <title>你使用新浪微博的主要目的是（可多选；选项较多，请您拖动右侧的滚动条查看所有内容）</title>
		<answer aid="a" score="1">关注新闻</answer>
		<answer aid="b" score="1">寻找信息</answer>
		<answer aid="c" score="1">关注喜欢的明星</answer>
		<answer aid="d" score="1">关注自己的同学</answer>
		<answer aid="e" score="1">玩游戏</answer>
		<answer aid="f" score="1">网上冲浪</answer>
		<answer aid="g" score="1">网上购物</answer>
		<answer aid="h" score="1">金融服务</answer>
		<answer aid="i" score="1">在线阅读报纸杂志</answer>
		<answer aid="j" score="1">在线社交</answer>
		<answer aid="k" score="1">发表个人评论</answer>
		<answer aid="l" score="1">为了完成工作和学习的必备工具</answer>
		<answer aid="m" score="1">为了寻求帮助</answer>
		<answer aid="n" score="1">为了参加某些活动的互动</answer>
		<answer aid="o" score="1" type="text">其他（请具体列出）</answer>
    </question>
	
	<question qid="q18" type="text">
		<title>您觉得使用新浪微博给您带来的好处有哪些？</title>
    </question>
	
	<question qid="q19" type="text">
		<title>您觉得新浪微博有哪些不足？</title>
    </question>
	
  </questions>

  <tags>
	<tag name="" label="致谢"><![CDATA[非常感谢您填写我们的问卷调查！]]></tag>
  </tags>
  
  <remarks>
    <remark minScore="min" maxScore="max">您的填写结果将用作科学研究之用。</remark>
  </remarks>

</questionnaire>
